### PR TITLE
Update lowRISC toolchain version

### PR DESCRIPTION
**Pull request by luismarques**
The new toolchain version includes:

- Support for the `.option noguards`.
- Fix for the jump guards hardening.

### CODE REVIEW

**Comment by luismarques** [comment]
This seems to work fine: https://github.com/lowRISC/opentitan/pull/16540
Shall we merge it? @alphan @cfrantz

**Comment by alphan** [comment]
> This seems to work fine: https://github.com/lowRISC/opentitan/pull/16540
> Shall we merge it? @alphan @cfrantz 

SGTM. The new features are disabled by default right? Do you think we need to diff the disassemblies just in case?

**Comment by luismarques** [comment]
> > This seems to work fine: [lowRISC/opentitan#16540](https://github.com/lowRISC/opentitan/pull/16540)
> > Shall we merge it? @alphan @cfrantz
> 
> SGTM. The new features are disabled by default right? Do you think we need to diff the disassemblies just in case?

When we adopt a new CRT version in OpenTitan we will get the jump guards that we merged in #5. So they aren't disabled by default, but that's unrelated to this PR. If you want to make them be disabled by default and manually enabled in the OT repo what's the proper way to do that? I can try to do another PR for that.

The OT PR to update the selected CRT version, and which will effectively enable the jump guards, is <https://github.com/lowRISC/opentitan/pull/16540> (it needs to be updated with a proper CRT version, now that this has been merged and we can do another versioned release). Yes, we should do a diff, though that was already discussed to some extent in #5.

**Comment by alphan** [comment]
> > > This seems to work fine: [lowRISC/opentitan#16540](https://github.com/lowRISC/opentitan/pull/16540)
> > > Shall we merge it? @alphan @cfrantz
> > 
> > 
> > SGTM. The new features are disabled by default right? Do you think we need to diff the disassemblies just in case?
> 
I'd suggest the following roll-out plan:

1. **Local experiments** If this feature is disabled by default, we can add a config in the `.bazelrc` file like:
```
build:with_jump_guards --copt='<OPTION_TO_ENABLE>'
```
so that we can enable it locally using `--config with_jump_guards`.  Note that we may need to use `--conlyopt` depending on how this option is defined. See [here](https://bazel.build/docs/user-manual#tool-flags) for more details. If the feature is enabled by default in the toolchain, we can disable it by default in our builds by also adding:
```
build --copt='<OPTION_TO_DISABLE>'
```
Assuming that we are confident with the correctness of the enable/disable logic in the toolchain the second flag above saves are from another toolchain release. At this phase we should thoroughly evaluate size and performance impact, review disassemblies, and make sure that there are no correctness issues.

2. **Enabled in the nightly pipeline** After some local experiments and analysis we can add the same build option to the nightly pipeline that @milesdai recently added. This will increase our confidence in this feature while not blocking any work. We can do this either by passing the correct config option to CI build scripts or changing the target definitions in `BUILD` files (and updating `.bazelrc` as needed). Obviously the first option would be easier to maintain.

3. **Enabled in the CI** We can flip the flags in `.bazelrc` so that this feature is enabled by default.

WDYT?

> 
> The OT PR to update the selected CRT version, and which will effectively enable the jump guards, is [lowRISC/opentitan#16540](https://github.com/lowRISC/opentitan/pull/16540) (it needs to be updated with a proper CRT version, now that this has been merged and we can do another versioned release). Yes, we should do a diff, though that was already discussed to some extent in #5.

Due to holidays, I'm ok with pointing to a commit for now and updating it to a release when we have it.

**Comment by luismarques** [comment]
> WDYT?

Why do we need to mess with `--copt`? Can't we just enable the feature in `.bazelrc`?

Context: Even though I now added that `.option noguards` construct to the toolchain, I think we should avoid enabling the jump guards hardening for the assembly files. Based on the documentation you linked to it seems we would need to use `--conlyopt` and `--cxxopt` to avoid adding that to assembly files as well.

I checked that we can change the `enabled = False` in CRT guards `feature` and then add `build --features=guards` to `.bazelrc`. Is there a reason why we'd prefer `build:with_jump_guards --copt='...'` instead? (I don't know much about Bazel).

**Comment by alphan** [comment]
> Why do we need to mess with `--copt`? Can't we just enable the feature in `.bazelrc`?

I'm not sure if I understand. I was also referring to the `.bazelrc` file.

**Pull request merged**
